# Generated by Django 4.2 on 2025-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_destination_created_at_destination_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
