# Generated by Django 4.2 on 2025-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(max_length=254)),
                ('phone_number_1', models.CharField(blank=True, max_length=15)),
                ('phone_number_2', models.CharField(blank=True, max_length=15)),
                ('Opening_Time', models.CharField(max_length=200)),
                ('Location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
