# Generated by Django 4.2 on 2025-07-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgourndImage', models.ImageField(blank=True, null=True, upload_to='homeslider/')),
                ('destinations', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
