# Generated by Django 4.2 on 2025-07-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_destination_slug'),
        ('pages', '0003_homeslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='destinations',
        ),
        migrations.AddField(
            model_name='homeslider',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.destination'),
            preserve_default=False,
        ),
    ]
