# Generated by Django 4.2 on 2025-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_hometourfacilites'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometourfacilites',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='hometour/'),
        ),
    ]
